### ISSUE TITLE
’EGNN_Sparse‘ object has no attribute '__check_input__'

### ISSUE THREAD

**Issue by wacharlin** [ykiiiiii/GraDe_IF#2]
Hi, i run the  `inverse_folding.ipynb` , and the fourth cell shows "AttributeError:'EGNN_Sparse' object has no attribute  _check_input_". The `torch_geometric` version is the same as yours, .2.2.0. and the new 2.4.0 also has  the bug. i don't know how to solve this bug. could you please help me?

![image](https://github.com/ykiiiiii/GraDe_IF/assets/38215077/4d36e271-22af-4e75-935f-e55aa1547c9d)

**Comment by ykiiiiii** [comment]
PYG changed the function name from '__check_input__' to '_check_input' in 2.3.0. If you run the code in torch-geometric==2.2.0 properly, it should be fine. Otherwise, you can change the function name to self._check_input in line 273. 

Hope it helps!

**Comment by wacharlin** [comment]
> PYG changed the function name from '**check_input**' to '_check_input' in 2.3.0. If you run the code in torch-geometric==2.2.0 properly, it should be fine. Otherwise, you can change the function name to self._check_input in line 273.
> 
> Hope it helps!

thanks! I think that maybe it is better to install the environment by oneself hhh. 

other excuse, if i could retrain this model? and could you release the step that train the model?  I see the `gradeif.py`. Thanks!
