### ISSUE TITLE
Last residue deleted

### ISSUE THREAD

**Issue by hnisonoff** [ykiiiiii/GraDe_IF#3]
I noticed on line 565 of `cath_imem_2nd.py` that you delete the last residue of the PDB file:
`graph = self.remove_node(graph, graph.x.shape[0]-1)`

Why is this done? Is it safe to comment out this line (code seems to run fine without it)? Is the last residue deleted when computing metrics with the baseline methods as well? 

Thanks!

**Comment by ykiiiiii** [comment]
Hi, thanks for pointing out this issue. I have removed this line and now the node number should be the same as the residue number. I used all residues when I computed the metrics.
