### ISSUE TITLE
no attribute '__check_input__'

### ISSUE THREAD

**Issue by QUEST2179** [ykiiiiii/GraDe_IF#5]
Dear developer,

try to run the example, but it gave an error

in egnn_pytorch_geometric.py
File "diffusion\model\egnn_pytorch\egnn_pytorch_geometric.py", line 250, in forward
    hidden_out, coors_out = self.propagate(edge_index, x=feats, edge_attr=edge_attr_feats,
  File "diffusion\model\egnn_pytorch\egnn_pytorch_geometric.py", line 273, in propagate
    size = self.__check_input__(edge_index, size)
AttributeError: 'EGNN_Sparse' object has no attribute '__check_input__'

after comment out #size = self.__check_input__(edge_index, size)
AttributeError: 'EGNN_Sparse' object has no attribute '__collect__'

**Comment by ykiiiiii** [comment]
Like #2 , pyg changed the function name from '__check_input__' to '_check_input'  and '__collect__' to '_collect' in 2.3.0. 

If you run the code in torch-geometric==2.2.0 properly, it should be fine. Otherwise, you can change the function name to self._check_input in line 273 and self._collect in line 274.

I modify the code to work for both version, it should work now.

**Comment by QUEST2179** [comment]
Thanks for pointing out. After changing to self._user_args in line 279, works great.

By the way, how to generate similar file to blosum_substitute.pt from a 'task-specific' transition matrix?

**Comment by ykiiiiii** [comment]
You can calculate an amino acid substitution matrix, similar to the  [https://en.wikipedia.org/wiki/BLOSUM](Blosum), using sequences from your protein family of interest, such as Multiple Sequence Alignment (MSA). Then, you can apply the softmax function with varying temperatures to generate transition matrices for different diffusion time steps.

Furthermore, it's possible to compute a position-wise transition matrix. Currently, we use a single transition matrix for all amino acids in a protein.
