### ISSUE TITLE
Questions about Perplexity

### ISSUE THREAD

**Issue by yukang123** [ykiiiiii/GraDe_IF#6]
Hi, I want to ask why the perplexity is multiplied by 0.01 at this line [perplexity](https://github.com/ykiiiiii/GraDe_IF/blob/1ccea1bd1d79a59a87ead52c7672314b238cb4fd/diffusion/gradeif.py#L620). 
What do you mean by saying "for the same scale" ? Thanks! @ykiiiiii

**Comment by ykiiiiii** [comment]
Hi, it is just for plotting. As single sample gives roughly 0.4 recovery rate and larger than 30 perplexity. Multiplying 0.01 just for plotting two metrics into one figure.

**Comment by yukang123** [comment]
Thanks for your reply! I am still confused why the perplexity is larger than 20. Since if we random pick residues from 20 types of amino acids, we will get the perplexity of 20.

**Comment by ykiiiiii** [comment]
During training, I only compute perplexity by the distribution of **one sample** , which is 'sharp' and has no distribution for some type of AA. This kind of distribution will lead to large perplexity, even worse than random select.

As shown in notebook, you can compute correct perplexity by integrating out $x_T$,

**Comment by yukang123** [comment]
Hi, I have a follow-up question. I am testing your method on the pdb file of a chain (ID: 6m71). But I got the score produced by torch.cross_entropy around 4. Is it reasonable? After doing the torch.exp(ll_fullseq), the perplexity will be very large.

**Comment by ykiiiiii** [comment]
> Hi, I have a follow-up question. I am testing your method on the pdb file of a chain (ID: 6m71). But I got the score produced by torch.cross_entropy around 4. Is it reasonable? After doing the torch.exp(ll_fullseq), the perplexity will be very large.

Hi, did you do ensemble? You can also switch diverse mode as True which will give you better result.

**Comment by llllly26** [comment]
Did you solve the problem of PPL? i met the same result. @yukang123 

> Hi, I have a follow-up question. I am testing your method on the pdb file of a chain (ID: 6m71). But I got the score produced by torch.cross_entropy around 4. Is it reasonable? After doing the torch.exp(ll_fullseq), the perplexity will be very large.
